security: 
  basic:
    enabled: false # turn of securing our application endpoints

management:
  security:
    enabled: true # turn of securing the actuator endpoints
    
logging:
  level:
    io:
      pivotal: DEBUG
       
greeting:
  displayFortune: false
   
quoteServiceURL: http://quote-service-dev.cfapps.io/quote